version: '3.7'
services:
  # app:
  #   container_name: "sample"
  #   ports:
  #      - 3000:3000
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  mongo:
    image: 'mongo:4.0-xenial'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sample

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
